"""use botusers table for user name cache and ban status

Revision ID: 013299acd044
Revises: 567ca09c82d0
Create Date: 2025-06-10 21:14:36.704884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '013299acd044'
down_revision: Union[str, None] = '567ca09c82d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('botusers',
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('is_feedback_banned', sa.Boolean(), nullable=False),
        sa.Column('user_name', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('user_id')
    )
    
    connection = op.get_bind()
    connection.execute(sa.text("""
        INSERT INTO botusers (user_id, user_name, is_feedback_banned)
        SELECT user_id, user_name, FALSE 
        FROM usernamecaches
    """))

    with op.batch_alter_table('usernamecaches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usernamecaches_user_id'))

    op.drop_table('usernamecaches')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usernamecaches',
        sa.Column('id', sa.INTEGER(), nullable=False),
        sa.Column('user_id', sa.INTEGER(), nullable=False),
        sa.Column('user_name', sa.VARCHAR(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )

    connection = op.get_bind()
    connection.execute(sa.text("""
        INSERT INTO usernamecaches (user_id, user_name)
        SELECT user_id, user_name
        FROM botusers
    """))


    with op.batch_alter_table('usernamecaches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usernamecaches_user_id'), ['user_id'], unique=1)

    op.drop_table('botusers')
    # ### end Alembic commands ###
