"""init

Revision ID: 567ca09c82d0
Revises: 
Create Date: 2025-06-10 19:11:05.780797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '567ca09c82d0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chats',
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('thing_name', sa.String(length=100), nullable=False),
    sa.Column('thing_form', sa.Enum('MASCULINE', 'FEMININE', 'MIDDLE', name='thingform'), nullable=False),
    sa.Column('thing_metric', sa.String(length=100), nullable=False),
    sa.Column('random_min_value', sa.Integer(), nullable=False),
    sa.Column('random_max_value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('chat_id')
    )
    op.create_table('usernamecaches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usernamecaches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usernamecaches_user_id'), ['user_id'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('thing_value', sa.Integer(), nullable=False),
    sa.Column('cooldown_timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.chat_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_chat_id'), ['chat_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_user_id'))
        batch_op.drop_index(batch_op.f('ix_users_chat_id'))

    op.drop_table('users')
    with op.batch_alter_table('usernamecaches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usernamecaches_user_id'))

    op.drop_table('usernamecaches')
    op.drop_table('chats')
    # ### end Alembic commands ###
